# Generated by Django 5.0.3 on 2024-04-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_helpcenter_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='helpcenter',
            options={},
        ),
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
        migrations.AlterModelTable(
            name='helpcenter',
            table='help_centers',
        ),
    ]
