# Generated by Django 4.2.6 on 2023-11-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_label',
            field=models.BooleanField(default=False),
        ),
    ]
