# Generated by Django 4.2.6 on 2024-01-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bath_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ванн'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bed_qty',
            field=models.PositiveIntegerField(verbose_name='Количество кроватей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bedroom_qty',
            field=models.PositiveIntegerField(verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guest_qty',
            field=models.PositiveIntegerField(verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_week',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за неделю'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rooms_qty',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='toilet_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество уборной'),
        ),
    ]
