# Generated by Django 4.2.6 on 2024-01-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_bath_qty_alter_product_bed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guests_with_babies',
            field=models.BooleanField(default=False, verbose_name='С ребенком'),
        ),
        migrations.AddField(
            model_name='product',
            name='guests_with_pets',
            field=models.BooleanField(default=False, verbose_name='С питомцем'),
        ),
    ]
