# Generated by Django 4.2.6 on 2024-01-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_guests_with_babies_product_guests_with_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guests_with_babies',
            field=models.BooleanField(default=True, verbose_name='С ребенком'),
        ),
    ]
