# Generated by Django 5.0.1 on 2024-01-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_guests_with_babies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='convenience',
            name='parent',
        ),
    ]
