# Generated by Django 5.0.1 on 2024-03-21 06:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_comment_parent_remove_convenience_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
