# Generated by Django 5.0.3 on 2024-04-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
    ]
