# Generated by Django 5.0.3 on 2024-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_product_pro_name_b60cd1_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date'], name='product_boo_start_d_fb6863_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['end_date'], name='product_boo_end_dat_4b7c2a_idx'),
        ),
    ]
