# Generated by Django 5.0.3 on 2024-04-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_booking_product_boo_start_d_fb6863_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_start_d_94c02c_idx',
            old_name='product_boo_start_d_fb6863_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_end_dat_49719f_idx',
            old_name='product_boo_end_dat_4b7c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_name_6f9890_idx',
            old_name='product_pro_name_b60cd1_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_price_p_82684a_idx',
            old_name='product_pro_price_p_19e502_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_rooms_q_c12fad_idx',
            old_name='product_pro_rooms_q_8d8793_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_guest_q_cfe819_idx',
            old_name='product_pro_guest_q_f9444d_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_type_id_104a22_idx',
            old_name='product_pro_type_id_9633ca_idx',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='convenience',
            table='conveniences',
        ),
        migrations.AlterModelTable(
            name='favorites',
            table='favorites',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
