# Generated by Django 5.0.1 on 2024-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'Модератор'), ('MANAGER', 'Менеджер'), ('DIRECTOR', 'Директор'), ('CLIENT', 'Клиент'), ('ADMIN', 'Админ')], default='CLIENT', max_length=100, verbose_name='Роль'),
        ),
    ]
